// Generate THIRD-PARTY-NOTICES.txt for every Auduio build (web, desktop, Android, iOS).
// Sources: `cargo metadata` of engine-rs and src-tauri (normal dependencies for Windows, macOS and Linux targets;
// licence + copyright lines read from each crate's own licence files), the Capacitor npm packages, the Android
// runtime libraries (Gradle), the fonts embedded in the manual PDF, and the VST 3 / CLAP API notices.
// Usage (from apps/): node scripts/gen-notices.mjs [out.txt ...]
//   default outputs: ../web-src/src/THIRD-PARTY-NOTICES.txt and ./THIRD-PARTY-NOTICES.txt
// Needs cargo (offline is fine once the crates are fetched) and node_modules installed.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const here = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const L = (f) => fs.readFileSync(path.join(here, 'scripts/licenses', f), 'utf8').trim();
const TARGETS = ['x86_64-pc-windows-msvc', 'aarch64-apple-darwin', 'x86_64-apple-darwin', 'x86_64-unknown-linux-gnu'];

function crates(dir) {
  const out = new Map();
  for (const t of TARGETS) {
    let m;
    try { m = JSON.parse(execFileSync('cargo', ['metadata', '--format-version', '1', '--offline', '--filter-platform', t], { cwd: path.join(here, dir), maxBuffer: 1 << 28 }).toString()); }
    catch (e) { m = JSON.parse(execFileSync('cargo', ['metadata', '--format-version', '1', '--filter-platform', t], { cwd: path.join(here, dir), maxBuffer: 1 << 28 }).toString()); }
    const byId = new Map(m.packages.map((p) => [p.id, p])), nodes = new Map(m.resolve.nodes.map((n) => [n.id, n])), ws = new Set(m.workspace_members);
    const seen = new Set(), st = [...ws];
    while (st.length) { const id = st.pop(); if (seen.has(id)) continue; seen.add(id); for (const d of nodes.get(id).deps) if (d.dep_kinds.some((k) => k.kind === null)) st.push(d.pkg); }
    for (const id of seen) if (!ws.has(id)) { const p = byId.get(id); out.set(p.name + ' ' + p.version, p); }
  }
  return out;
}
const COPY_RE = /^\s*(?:\/\/|#|\*)?\s*(copyright\b.*|\(c\)\s*\d.*|©.*)$/i;
function licenceFiles(dir) { try { return fs.readdirSync(dir).filter((f) => /^(licen[cs]e|copying|notice|copyright)/i.test(f)).map((f) => path.join(dir, f)); } catch (e) { return []; } }
function copyrights(p) {
  const lines = new Set();
  for (const f of licenceFiles(path.dirname(p.manifest_path))) for (const l of fs.readFileSync(f, 'utf8').split(/\r?\n/)) {
    const m = l.match(COPY_RE); if (!m) continue; const s = m[1].trim();
    if (/copyright (notice|holders?|owner|law|and license|statement)|copyright\s*$|the above copyright|\[yyyy\]|\{yyyy\}|<year>|copyright \[|copyright \(c\) <|Copyright license/i.test(s)) continue;
    lines.add(s.replace(/\s+/g, ' '));
  }
  if (!lines.size && p.authors && p.authors.length) lines.add('Copyright (c) ' + p.authors.join(', ').replace(/\s*<[^>]*>/g, ''));
  if (!lines.size) lines.add(`Copyright (c) the ${p.name} authors`);
  return [...lines].slice(0, 6);
}
const pick = (expr) => { const e = (expr || 'UNKNOWN').replace(/\//g, ' OR ');
  if (/\bAND\b/.test(e)) return e.replace(/[()]/g, '').split(/\s+AND\s+/).map((x) => pick(x)).join(' AND ');
  const alts = e.split(/\s+OR\s+/).map((x) => x.replace(/[()]/g, '').trim());
  for (const pref of ['MIT', 'Apache-2.0', 'BSD-3-Clause', 'BSD-2-Clause', 'ISC', 'Zlib', 'Unicode-3.0', 'MPL-2.0']) if (alts.includes(pref)) return pref;
  return alts[0]; };
const withTextInline = /BSD|ISC|Zlib|Unicode|MPL|0BSD|CC0|Unlicense/; // print the crate's own licence file (holds its copyright)

let txt = `THIRD-PARTY SOFTWARE NOTICES AND INFORMATION
Auduio (web app, desktop app for Windows / macOS / Linux, Android and iOS apps)
Generated ${new Date().toISOString().slice(0, 10)} by apps/scripts/gen-notices.mjs

Auduio's own code is not covered by this file (see LICENSE). Auduio's sounds, drum kits, wavetables, reverb
impulse responses and icons are generated by Auduio's own code or drawn for Auduio; no third-party samples,
presets or icon sets are bundled. The app uses the fonts already installed on your device.

Trademarks: VST is a trademark of Steinberg Media Technologies GmbH, registered in Europe and other countries.
All other product names are the property of their respective owners; Auduio is not affiliated with or
endorsed by them. Auduio shows no VST logo.

Privacy: Auduio has no accounts, no analytics, no telemetry and no ads, and it does not send your projects
or recordings anywhere. See About > Privacy in the app.

MP3: Auduio decodes MP3 files with the decoder built into the browser / operating system; it does not
contain its own MP3 codec. The MP3 patents have expired (2017).

===========================================================================================================
1. PLUGIN APIs (desktop app, native audio engine)
===========================================================================================================

VST 3 API. The engine talks to VST 3 plugins through Rust bindings (crate "vst3") generated from the VST 3 SDK
3.8.0 interface headers, which are licensed under the MIT licence:

${L('VST3-SDK-MIT.txt').replace(/^\/\/-+\s*$/gm, '').trim()}

CLAP (CLever Audio Plugin API), used through the crate "clap-sys":

${L('CLAP-MIT.txt')}
`;
const sections = [['engine-rs', '2. NATIVE AUDIO ENGINE (desktop app: auduio-engine, Rust crates)'], ['src-tauri', '3. DESKTOP APP SHELL (Tauri, Rust crates)']];
const licCount = new Map(); const all = [];
for (const [dir, title] of sections) {
  const list = [...crates(dir).values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
  txt += `\n===========================================================================================================\n${title}\n===========================================================================================================\n`;
  txt += `${list.length} packages. Where a package offers a choice of licences, Auduio uses it under the licence shown.\nFull licence texts are in section 7.\n\n`;
  for (const p of list) {
    const lic = pick(p.license); licCount.set(lic, (licCount.get(lic) || 0) + 1); all.push([dir, p.name, p.version, p.license, lic, path.dirname(p.manifest_path)]);
    txt += `- ${p.name} ${p.version}  [${lic}]${p.license && pick(p.license) !== p.license ? ` (offered: ${p.license})` : ''}${p.repository ? '  ' + p.repository : ''}\n`;
    for (const c of copyrights(p)) txt += `    ${c}\n`;
    if (withTextInline.test(lic)) { const f = licenceFiles(path.dirname(p.manifest_path)).find((x) => !/apache|mit/i.test(path.basename(x))) || licenceFiles(path.dirname(p.manifest_path))[0]; if (f && !/MPL/.test(lic)) txt += '\n' + fs.readFileSync(f, 'utf8').trim().split('\n').map((l) => '    ' + l).join('\n') + '\n\n'; }
    for (const f of licenceFiles(path.dirname(p.manifest_path)).filter((x) => /^notice/i.test(path.basename(x)))) txt += '    NOTICE:\n' + fs.readFileSync(f, 'utf8').trim().split('\n').map((l) => '    ' + l).join('\n') + '\n';
  }
}
// ---- npm (Capacitor) + Android runtime
txt += `\n===========================================================================================================\n4. MOBILE APP SHELLS (Android / iOS: Capacitor)\n===========================================================================================================\n`;
for (const n of ['@capacitor/core', '@capacitor/android', '@capacitor/ios']) {
  try { const d = path.join(here, 'node_modules', n); const j = JSON.parse(fs.readFileSync(path.join(d, 'package.json'), 'utf8'));
    txt += `- ${j.name} ${j.version}  [${j.license}]  ${(j.repository && (j.repository.url || j.repository)) || ''}\n`;
    const lf = licenceFiles(d)[0]; if (lf) for (const l of fs.readFileSync(lf, 'utf8').split('\n')) { const m = l.match(COPY_RE); if (m) txt += `    ${m[1].trim()}\n`; }
  } catch (e) { txt += `- ${n}  [MIT]\n`; }
}
txt += `
Android runtime libraries (Apache License 2.0, full text in section 7):
- AndroidX libraries (activity, annotation, appcompat, arch-core, collection, concurrent-futures, coordinatorlayout,
  core, core-ktx, core-splashscreen, core-viewtree, cursoradapter, customview, drawerlayout, emoji2, fragment,
  interpolator, lifecycle, loader, profileinstaller, resourceinspection, savedstate, startup, tracing,
  vectordrawable, versionedparcelable, viewpager, webkit)  Copyright The Android Open Source Project
- Kotlin standard library, kotlinx.coroutines, JetBrains annotations  Copyright JetBrains s.r.o. and Kotlin Programming Language contributors
- Guava ListenableFuture  Copyright The Guava Authors
- JSpecify annotations  Copyright The JSpecify Authors
- Apache Cordova Android framework 14.0.1 (bundled by Capacitor for plugin compatibility)
    NOTICE:
${L('Cordova-NOTICE.txt').split('\n').map((l) => '    ' + l).join('\n')}
`;
// ---- fonts in the manual
txt += `\n===========================================================================================================\n5. FONTS EMBEDDED IN THE MANUAL (Auduio-Manual.pdf)\n===========================================================================================================\n
DejaVu Sans (subset). DejaVu changes are in the public domain; Bitstream Vera glyphs are under the Bitstream Vera
licence, Arev glyphs under the Arev licence:

${L('DejaVu-fonts.txt')}

Noto Sans (subset), SIL Open Font License 1.1:

${L('OFL-1.1-NotoSans.txt')}
`;
txt += `\n===========================================================================================================\n6. INSTALLERS\n===========================================================================================================\n
Windows installers are built with NSIS (zlib licence) and the WiX Toolset; the Windows installer may download
Microsoft's WebView2 runtime bootstrapper from Microsoft when WebView2 is missing. On Linux Auduio ships as a .deb
package only; it uses WebKitGTK, GStreamer and ALSA from your system (installed by your distribution under their own
licences) and does not bundle them.
`;
txt += `\n===========================================================================================================\n7. LICENCE TEXTS\n===========================================================================================================\n
MIT License (the copyright line for each package is listed with the package above)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of
the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.

-----------------------------------------------------------------------------------------------------------
Mozilla Public License 2.0 (cssparser, cssparser-macros, dtoa-short, selectors, option-ext: used unmodified;
their source code is available from https://crates.io and the repositories listed above). Full text:
https://www.mozilla.org/MPL/2.0/
${(() => { const d = all.find((a) => a[4] === 'MPL-2.0'); const f = d && licenceFiles(d[5])[0]; return f ? '\n' + fs.readFileSync(f, 'utf8').trim() + '\n' : ''; })()}
-----------------------------------------------------------------------------------------------------------
Apache License 2.0

${L('Apache-2.0.txt')}
`;
const outs = process.argv.slice(2).length ? process.argv.slice(2) : [path.resolve(here, '../web-src/src/THIRD-PARTY-NOTICES.txt'), path.resolve(here, 'THIRD-PARTY-NOTICES.txt')];
for (const o of outs) { fs.mkdirSync(path.dirname(o), { recursive: true }); fs.writeFileSync(o, txt); console.log('wrote', o, txt.length, 'bytes'); }
fs.writeFileSync(path.join(here, 'scripts/licenses/inventory.json'), JSON.stringify(all.map((a) => a.slice(0, 5)), null, 1));
console.log([...licCount].map(([k, v]) => `${v} x ${k}`).join(', '));
