import { chromium } from 'playwright-core';
import { spawn } from 'node:child_process';
import path from 'node:path';
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const PORT = +(process.env.PORT || 8765);
const server = spawn('node', [path.join(ROOT, 'tools/serve.mjs'), path.join(ROOT, 'dist'), String(PORT), '/daw/'], { stdio: 'pipe' });
await new Promise((r) => server.stdout.once('data', r));
const browser = await chromium.launch({ headless: true, args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', '--autoplay-policy=no-user-gesture-required', '--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['microphone'] });
await ctx.addInitScript(() => { localStorage.setItem('webdaw.prefs', JSON.stringify({ guideDone: true, tutorialDone: true, phoneMode: 'off' })); document.addEventListener('securitypolicyviolation', (e) => console.error('CSP ' + e.violatedDirective + ' ' + e.blockedURI)); });
const page = await ctx.newPage();
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log('[' + m.type() + ']', m.text()); });
page.on('pageerror', (e) => console.log('[pageerror]', e.message, e.stack));
await page.goto(`http://localhost:${PORT}/daw/?nosw`);
await page.click('#startBtn');
await page.waitForSelector('#sessionView .col[data-id]', { timeout: 15000 });
console.log('started');
await page.evaluate(async () => { const b = [...document.querySelectorAll('.add-track')].find((x) => x.textContent.includes('Synth')); b.click(); });
await page.waitForTimeout(300);
await page.screenshot({ path: path.join(ROOT, 'screenshots/v2/smoke.png') });
console.log(await page.evaluate(() => JSON.stringify({ tracks: __daw.S.project.tracks.map((t) => t.kind + ':' + (t.inst && t.inst.type)), devices: document.querySelectorAll('#devices .device').length })));
await browser.close(); server.kill();
